### ISSUE TITLE
[Log] grade is not shown on new entries

### ISSUE THREAD

**Issue by salamca** [plezanje-net/web#54]

**Comment by MaticDiba** [comment]
Short discussion:
Right now if route is logged and user didn't specify his own grade proposal, null value will be stored under `grade` column. `difficulty` will be always null, because this is a calculated value which is never calculated on log form.

I propose this solution:
```typescript
    const routes = this.routes.value.map((route: any, i: number) => {
      return {
        date: route.date || activity.date,
        partner: route.partner || activity.partners,
        ascentType: route.ascentType,
        notes: route.notes,
        position: i,
        publish: route.publish,
        routeId: route.routeId,
        name: route.name,
        difficulty: route.difficulty,
        grade: route.publish === PublishOptionsEnum.private ? undefined : route.gradeSuggestion ?? route.grade,
        stars: route.stars,
      };
    });
```
Question 1: what should be done with difficulty?
Question 2: if users proposed grade is stored under `grade` then he will also see that grade in his log. Is this ok?
Question 3: is it really ok to have undefined if this is private. In this case, the user will always have private entires without any grade.

Was there any discussion about this already?

**Comment by MaticDiba** [comment]
As discussed: for now we will not store proposed grade to `activity_route` table. 

On listings, value from `activity_route.route.grade` should be used.

`route.grade` will be calculated (updated) in another task.

**Comment by salamca** [comment]
closing this as not relevant anymore/has been solved in another pr.
